name: Build and Push

on:
  push:
    branches: [main]
    paths-ignore:
      - 'docs/**'
      - '**.md'
      - '.github/**'
      - '.tekton/**'

jobs:
  # Ensure that tests pass before publishing a new image.
  build:
    runs-on: ubuntu-latest
    env:
      IMAGE_NAME: kserve/modelmesh-controller
      IMAGE_TAG: latest
      CI: true
    steps:
      - uses: actions/checkout@v2
      - name: Build develop image
        run: make build.develop
      - name: Run lint
        run: ./scripts/develop.sh make fmt
      - name: Run unit tests
        run: ./scripts/develop.sh make test
      # Depend on nightly builds for pushing for now.
      # - name: Build runtime image
      #   run: make build
      # - name: Log in to Docker Hub
      #   run: docker login -u ${{ secrets.DOCKER_USER }} -p ${{ secrets.DOCKER_ACCESS_TOKEN }}
      # - name: Push to Docker Hub
      #   run: docker push ${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}
